### ISSUE TITLE
Shorten Typography-Related Variables

### ISSUE THREAD

**Issue by johndjameson** [spellbook/css#2]
Variables like these are redundant: 

```scss
$t-fontFamily: sans-serif;
$t-fontSize: 16px;
```

These are more concise:

```scss
$t-family: sans-serif;
$t-size: 16px;
```

The `t-` implies that they’re font-related properties, so we can drop the word `font`.

**Comment by drewbarontini** [comment]
My only concern here would be that we'd lose the `propertyName` convention that we use across all variables. I'm not against it, but just something to consider.

**Comment by dandenney** [comment]
Do we need `t-` settings at all? With tools going to something like `sb-ff-heading` or `sb-ffh`, could these base items be `$fontFamily` or `$fF` (that one is gross)?

Aside from the very base sitewide text, these get overridden so could it be handled as a base item?

**Comment by johndjameson** [comment]
@drewbarontini Yeah, the consistency with the property names is probably easier to manage. Less thought involved and they should sort more intuitively.

@dandenney I think anything global needs a prefix for searchability. Variables without one are okay in one-off cases like this though:

``` scss
.sb-badge {
  $color: red;
  $size: 80px;
  color: $color;
  height: $size;
  width: $size;

  &:hover {
    color: darken($color, 5%);
  }
}
```

But even then we might make `$badge-color` or `$badge-size` variables if we need in elsewhere in the module.
